ENTITY_REGISTRY = [
    {
        "canonical": "AMAZON",
        "aliases": ["AMAZON", "AMAZON PAY", "AMZN"],
        "category": "E-COMMERCE",
        "role": "merchant",
        "confidence": 0.88,
        "ambiguity": "MEDIUM",
    },
    {
        "canonical": "FLIPKART",
        "aliases": ["FLIPKART", "FLIPKARTPAYMEN", "AULT EXPRESS FLIPKART", "EKART"],
        "category": "E-COMMERCE",
        "role": "merchant",
        "confidence": 0.92,
        "ambiguity": "LOW",
    },
    {
        "canonical": "SWIGGY",
        "aliases": ["SWIGGY"],
        "category": "E-COMMERCE",
        "role": "merchant",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "ZOMATO",
        "aliases": ["ZOMATO"],
        "category": "E-COMMERCE",
        "role": "merchant",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "SUPER FILLINGS",
        "aliases": ["SUPER FILLINGS"],
        "category": "FUEL",
        "role": "merchant",
        "confidence": 0.93,
        "ambiguity": "LOW",
    },
    {
        "canonical": "BPCL",
        "aliases": ["BPCL", "BHARAT PETROLEUM"],
        "category": "FUEL",
        "role": "merchant",
        "confidence": 0.86,
        "ambiguity": "MEDIUM",
    },
    {
        "canonical": "HPCL",
        "aliases": ["HPCL", "HINDUSTAN PETROLEUM"],
        "category": "FUEL",
        "role": "merchant",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "INDIAN OIL",
        "aliases": ["INDIAN OIL", "IOCL"],
        "category": "FUEL",
        "role": "merchant",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "IRCTC",
        "aliases": ["IRCTC"],
        "category": "TRAVEL",
        "role": "merchant",
        "confidence": 0.95,
        "ambiguity": "LOW",
    },
    {
        "canonical": "MAKEMYTRIP",
        "aliases": ["MAKEMYTRIP", "MAKE MY TRIP"],
        "category": "TRAVEL",
        "role": "merchant",
        "confidence": 0.92,
        "ambiguity": "LOW",
    },
    {
        "canonical": "YATRA",
        "aliases": ["YATRA"],
        "category": "TRAVEL",
        "role": "merchant",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "LIC",
        "aliases": ["LIC", "LIFE INSURANCE CORPORATION"],
        "category": "INSURANCE",
        "role": "insurer",
        "confidence": 0.95,
        "ambiguity": "LOW",
    },
    {
        "canonical": "APY",
        "aliases": ["APY", "PRAN"],
        "category": "INSURANCE",
        "role": "insurer",
        "confidence": 0.86,
        "ambiguity": "MEDIUM",
    },
    {
        "canonical": "AIRTEL",
        "aliases": ["AIRTEL"],
        "category": "RECHARGE",
        "role": "telecom",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "JIO",
        "aliases": ["JIO", "JIO POSTPAID"],
        "category": "RECHARGE",
        "role": "telecom",
        "confidence": 0.88,
        "ambiguity": "LOW",
    },
    {
        "canonical": "BESCOM",
        "aliases": ["BESCOM"],
        "category": "UTILITY",
        "role": "biller",
        "confidence": 0.92,
        "ambiguity": "LOW",
    },
    {
        "canonical": "BAJAJ FINANCE",
        "aliases": ["BAJAJ FINANCE", "BAJAJ FINANCELTD"],
        "category": "LOAN",
        "role": "lender",
        "confidence": 0.88,
        "ambiguity": "MEDIUM",
    },
    {
        "canonical": "HDB FINANCIAL SERVICES",
        "aliases": ["HDB FINANCIAL SERVICES", "HDBFINANCIALSERVIC", "HDB FINANCIAL", "HDBFIN"],
        "category": "LOAN",
        "role": "lender",
        "confidence": 0.92,
        "ambiguity": "LOW",
    },
    {
        "canonical": "GROWTH SOURCE FINANCE",
        "aliases": ["GROWTH SOURCE FINANCE", "GROWTHSOURCEFINANC", "GROWTH SOURCE FINANC"],
        "category": "LOAN",
        "role": "lender",
        "confidence": 0.90,
        "ambiguity": "LOW",
    },
    {
        "canonical": "CRED",
        "aliases": ["CRED", "PAID VIA CRED", "PAIDVIACRED"],
        "category": "CREDIT CARD PAYMENT",
        "role": "card_payment_app",
        "confidence": 0.82,
        "ambiguity": "MEDIUM",
    },
    {
        "canonical": "PHONEPE",
        "aliases": ["PHONEPE", "PHONE PE"],
        "category": "PAYMENT GATEWAY",
        "role": "payment_channel",
        "confidence": 0.58,
        "ambiguity": "HIGH",
    },
    {
        "canonical": "PAYTM",
        "aliases": ["PAYTM", "ONE 97", "ONE97", "ONE 97 COMMUNICATIONS"],
        "category": "PAYMENT GATEWAY",
        "role": "payment_processor",
        "confidence": 0.72,
        "ambiguity": "MEDIUM",
    },
    {
        "canonical": "MOBIKWIK",
        "aliases": ["MOBIKWIK"],
        "category": "PAYMENT GATEWAY",
        "role": "wallet",
        "confidence": 0.70,
        "ambiguity": "MEDIUM",
    },
    {
        "canonical": "RAZORPAY",
        "aliases": ["RAZORPAY"],
        "category": "PAYMENT GATEWAY",
        "role": "payment_processor",
        "confidence": 0.80,
        "ambiguity": "MEDIUM",
    },
    {
        "canonical": "PAYU",
        "aliases": ["PAYU", "PAY U"],
        "category": "PAYMENT GATEWAY",
        "role": "payment_processor",
        "confidence": 0.80,
        "ambiguity": "MEDIUM",
    },
    {
        "canonical": "BILLDESK",
        "aliases": ["BILLDESK", "BILL DESK"],
        "category": "PAYMENT GATEWAY",
        "role": "payment_processor",
        "confidence": 0.78,
        "ambiguity": "MEDIUM",
    },
]
